# Generated by Django 5.2.3 on 2025-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='eventType',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
