# Generated by Django 5.2.3 on 2025-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
