# Generated by Django 5.2.3 on 2025-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_lat_venue_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
