# Generated by Django 5.2.3 on 2025-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=500),
        ),
    ]
