# Generated by Django 5.2.3 on 2025-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
