# Generated by Django 5.2.3 on 2025-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
