# Generated by Django 5.2.4 on 2025-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_favoritevenue_venuerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
