# Generated by Django 5.2.4 on 2025-09-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_average_rating'),
        ('venues', '0009_venue_location_name'),
    ]

    operations = [
    ]
