# Generated by Django 5.2.4 on 2025-09-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_merge_20250903_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='venue',
        ),
    ]
