# Generated by Django 5.2.4 on 2025-09-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_service_venue_venueimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='eventType',
        ),
    ]
