# Generated by Django 5.2.4 on 2025-09-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_remove_venue_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('snack', 'Snack'), ('main_course', 'Main Course')], max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_items', to='venues.venue')),
            ],
        ),
    ]
