# Generated by Django 5.2.4 on 2025-09-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='service',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='venue',
        ),
        migrations.DeleteModel(
            name='CateringItem',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
