# Generated by Django 5.2.4 on 2025-09-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_remove_eventtype_venue_remove_service_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='average_rating',
        ),
        migrations.DeleteModel(
            name='VenueRating',
        ),
    ]
