# Generated by Django 5.2.4 on 2025-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0002_eventtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(upload_to='venue_images/'),
        ),
    ]
