# Generated by Django 5.2.3 on 2025-07-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Venue Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
