# Generated by Django 5.2.4 on 2025-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0004_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('venue_owner', 'Venue Owner'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
